CREATE DATABASE Desafio;
USE Desafio;
CREATE TABLE Tasks (
	id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	title NVARCHAR(200) NOT NULL,
	description TEXT,
	status NVARCHAR(100) NOT NULL,
	date_create DATE
)